import { Inter } from 'next/font/google'
import './globals.css'
import Script from 'next/script'

const KAKAO_API_KEY = process.env.NEXT_PUBLIC_KAKAO_APP_JS_KEY
const KAKAO_SDK_URL = `//dapi.kakao.com/v2/maps/sdk.js?appkey=${KAKAO_API_KEY}&autoload=false`
//https://react-kakao-maps-sdk.jaeseokim.dev/docs/intro

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {children}
        <Script src={KAKAO_SDK_URL} strategy='beforeInteractive'></Script>
      </body>
    </html>
  )
}
